"""
Things to consider:
- Access to the values generated by sensor (voltages)
- Possible use cases given created methods

To ask about:
- What methods to include
- Update dynamically to server and pull necessary information from server
"""

class SoundDetector:
    # Constructor to make SoundDetector object
    def __init__(self, gate_pin, audio_pin, envelope_pin):
        self._gate_pin = gate_pin              # Has a gate pin
        self._audio_pin = audio_pin            # Has an audio pin
        self._envelope_pin = envelope_pin      # Has an envelope pin

    # Retrieves value of Gate
    def get_gate(self):
        return self._gate_pin

    # Retrieves value of Audio
    def get_audio(self):
        return self._audio_pin

    # Retrieves value of Envelope
    def get_envelope(self):
        return self._audio_pin
